// IMDB TOP 100 Movies
module.exports = [
  
"The Shape of Water",
"The Greatest Showman" ,
"Jumanji: Welcome to the Jungle",
"Three Billboards Outside Ebbing, Missouri",
"Star Wars: The Last Jedi",
"Tonya",
"Lady Bird",
"Darkest Hour",
"The Disaster Artist",
"Bright",
"Blade Runner",
"Molly's Game",
"Insidious: The Last Key",
"Call Me by Your Name",
"It",
"The Post",
"Coco",
"Red Sparrow",
"Black Panther",
"Pitch Perfect",
"Avengers: Infinity War",
"Dunkirk",
"Thor: Ragnarok",
"Justice League",
"All the Money in the World",
"Hostiles",
"The Commuter",
"The Room",
"Get Out",
"Solo: A Star Wars Story",
"Downsizing",
"Jigsaw",
"Phantom Thread",
"Pirates of the Caribbean: Dead Men Tell No Tales",
"X-Men: Dark Phoenix",
"Kingsman: The Golden Circle",
"Ferdinand",
"The Foreigner",
"American Made",
"Mother! ",
"Tully",
"Wonder",
"The Snowman",
"Venom",
"Paddington 2",
"Tomb Raider",
"Logan",
"Battle of the Sexes",
"Guardians of the Galaxy Vol. 2",
"Blade Runner",
"The Florida Project",
"Happy Death Day",
"Day of the Dead: Bloodline",
"Proud Mary",
"Slender Man",
"12 Strong",
"Baby Driver",
"The Mountain Between Us",
"The Killing of a Sacred Deer",
"Fifty Shades Freed",
"Ready Player One",
"Murder on the Orient Express",
"Logan Lucky",
"Wind River",
"The Godfather",
"Jumanji",
"Wonder Woman",
"The Predator",
"A Bad Moms Christmas",
"Untitled Deadpool Sequel",
"King Arthur: Legend of the Sword",
"Beauty and the Beast",
"Harry Potter and the Sorcerer's Stone",
"Spider-Man: Homecoming",
"The Big Sick",
"M:I 6 - Mission Impossible",
"Den of Thieves",
"Fantastic Beasts: The Crimes of Grindelwald",
"Atomic Blonde",
"Blockers",
"Aquaman",
"The Strangers: Prey at Night",
"Arif v 216",
"Star Wars: The Force Awakens",
"Acts of Violence",
"Valerian and the City of a Thousand Planets",
"Rogue One: A Star Wars Story",
"The Irishman",
"Loving Vincent",
"What Happened to Monday",
"In the Fade",
"Kong: Skull Island",
"The Vault",
"Maze Runner: The Death Cure",
"Geostorm",
"The Hitman's Bodyguard",
"Wonder Wheel",
"You Were Never Really Here",
"Flatliners",
"The Shawshank Redemption"
];
